--- 
name: LazyLoader
category: Utilities
tags: [lazy, loader, lazy loading, structure, pattern]
current: 0.1
author: davidck
contact: davidck@gmail.com
demo: http://www.staticdynamic.ca/reol/LazyLoader/Demos/
website: http://www.reol.com
